language: node_js
sudo: required
cache: false
os:
  - linux
node_js:
  - "11.9.0"
services:
  - xvfb
addons:
  chrome: stable
  firefox: stable
script:
- travis_retry npm install --depth 0 --silent
- npm run lint
- npm run build
- travis_retry npm run test
